# Generated by Django 3.0 on 2020-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alive', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=12)),
                ('age', models.SmallIntegerField()),
                ('addr', models.CharField(max_length=123)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'test_emp',
            },
        ),
    ]
